### ISSUE TITLE
5.4.3展示不全

### ISSUE THREAD

**Issue by xiaohong001** [ivanhao/PveSensors#2]
![image](https://user-images.githubusercontent.com/5635317/63652433-a3df8c00-c792-11e9-89af-c8b81a5c902c.png)

**Comment by ivanhao** [comment]
需要执行sensors-detect ,一路YES即可
执行后查看提示找到什么模块，然后通过modprobe进行加载，例如：
mobprobe coretemp 
注意找到的模块应该不止一个

**Comment by ivanhao** [comment]
> ![image](https://user-images.githubusercontent.com/5635317/63652433-a3df8c00-c792-11e9-89af-c8b81a5c902c.png)

需要执行sensors-detect ,一路YES即可
执行后查看提示找到什么模块，然后通过modprobe进行加载，例如：
mobprobe coretemp
注意找到的模块应该不止一个
